<?php

namespace Database\Seeders;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlantSeeder extends Seeder
{
    public function run()
    {
        $plants = [
            ['namaplant' => 'ANCOL', 'lokasi' => ''],
            ['namaplant' => 'BALARAJA', 'lokasi' => ''],
            ['namaplant' => 'BANDUNG', 'lokasi' => ''],
            ['namaplant' => 'BANDUNG 2', 'lokasi' => ''],
            ['namaplant' => 'BATANG 2', 'lokasi' => ''],
            ['namaplant' => 'BOGOR BARAT', 'lokasi' => ''],
            ['namaplant' => 'BP. LAWANG', 'lokasi' => ''],
            ['namaplant' => 'CIANJUR', 'lokasi' => ''],
            ['namaplant' => 'CIBEET', 'lokasi' => ''],
            ['namaplant' => 'CIBITUNG', 'lokasi' => ''],
            ['namaplant' => 'CIGUDEG', 'lokasi' => ''],
            ['namaplant' => 'CIJUREY', 'lokasi' => ''],
            ['namaplant' => 'CIKARANG', 'lokasi' => ''],
            ['namaplant' => 'CIKARANG 2', 'lokasi' => ''],
            ['namaplant' => 'CILACAP', 'lokasi' => ''],
            ['namaplant' => 'CILEGON', 'lokasi' => ''],
            ['namaplant' => 'CILEGON 2', 'lokasi' => ''],
            ['namaplant' => 'CIWANDAN', 'lokasi' => ''],
            ['namaplant' => 'DADAP', 'lokasi' => ''],
            ['namaplant' => 'DEPOK', 'lokasi' => ''],
            ['namaplant' => 'GADING SERPONG', 'lokasi' => ''],
            ['namaplant' => 'GEDANGAN', 'lokasi' => ''],
            ['namaplant' => 'GUNUNG HALU', 'lokasi' => ''],
            ['namaplant' => 'JATIWARNA', 'lokasi' => ''],
            ['namaplant' => 'JDRSIB', 'lokasi' => ''],
            ['namaplant' => 'JURUMUDI', 'lokasi' => ''],
            ['namaplant' => 'KALIBARU', 'lokasi' => ''],
            ['namaplant' => 'KANCI', 'lokasi' => ''],
            ['namaplant' => 'KANCI PEJAGAN', 'lokasi' => ''],
            ['namaplant' => 'KARANGKANDRI', 'lokasi' => ''],
            ['namaplant' => 'KEDIRI', 'lokasi' => ''],
            ['namaplant' => 'KEMBANGAN', 'lokasi' => ''],
            ['namaplant' => 'KRAWANG', 'lokasi' => ''],
            ['namaplant' => 'MARUNDA', 'lokasi' => ''],
            ['namaplant' => 'NAROGONG', 'lokasi' => ''],
            ['namaplant' => 'ONSITE 1', 'lokasi' => ''],
            ['namaplant' => 'ONSITE CISUMDAWU', 'lokasi' => ''],
            ['namaplant' => 'ONSITE PAMANUKAN', 'lokasi' => ''],
            ['namaplant' => 'PANDAAN', 'lokasi' => ''],
            ['namaplant' => 'PANGALENGAN', 'lokasi' => ''],
            ['namaplant' => 'PONDOK INDAH', 'lokasi' => ''],
            ['namaplant' => 'PONDOK INDAH 1', 'lokasi' => ''],
            ['namaplant' => 'PULOGADUNG 1', 'lokasi' => ''],
            ['namaplant' => 'PULOGADUNG 2', 'lokasi' => ''],
            ['namaplant' => 'PULOGADUNG 3', 'lokasi' => ''],
            ['namaplant' => 'RANGKAS', 'lokasi' => ''],
            ['namaplant' => 'RAWA TERATE', 'lokasi' => ''],
            ['namaplant' => 'SEMARANG 2', 'lokasi' => ''],
            ['namaplant' => 'SEMARANG new', 'lokasi' => ''],
            ['namaplant' => 'SENTUL', 'lokasi' => ''],
            ['namaplant' => 'SERANG', 'lokasi' => ''],
            ['namaplant' => 'SERPONG', 'lokasi' => ''],
            ['namaplant' => 'SUBANG', 'lokasi' => ''],
            ['namaplant' => 'SUMEDANG', 'lokasi' => ''],
            ['namaplant' => 'SUMMARECON BEKASI', 'lokasi' => ''],
            ['namaplant' => 'SURALAYA 1', 'lokasi' => ''],
            ['namaplant' => 'SURALAYA 2', 'lokasi' => ''],
            ['namaplant' => 'TANJUNG SARI', 'lokasi' => ''],
            ['namaplant' => 'THAMRIN 2', 'lokasi' => ''],
            ['namaplant' => 'TUBAN', 'lokasi' => ''],
            ['namaplant' => 'TUBAN JETTY', 'lokasi' => ''],
            ['namaplant' => 'VP JAWA TENGAH', 'lokasi' => ''],
            ['namaplant' => 'VP SERPONG', 'lokasi' => ''],
            ['namaplant' => 'VP01 JAKARTA', 'lokasi' => ''],
            ['namaplant' => 'VP02 BANTEN', 'lokasi' => ''],
            ['namaplant' => 'VP05 EAST JAVA', 'lokasi' => ''],
            ['namaplant' => 'VUB TUBAN', 'lokasi' => ''],
            ['namaplant' => 'YOGYAKARTA', 'lokasi' => ''],
            ['namaplant' => 'Avatar BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Balusu BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Bandar Marsilam Simalungun BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Bangkalan BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Bantul BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Banyuputih BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Batang Gringsing BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Batukliang BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Bayung Lencir MusiBanyuasin Proyek BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Bitung BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Bontang BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Bontang Selatan CPO Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Brebes Wanasari 2 BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'BSP CPO Bontang', 'lokasi' => ''],
            ['namaplant' => 'Gresik BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Jenu Tuban Proyek BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Kadirogo BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Karang Tengah Demak BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Kutai Timur Teluk Pandan BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Makassar BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Paiton Probolinggo Proyek BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'PakCrete Small Bag', 'lokasi' => ''],
            ['namaplant' => 'Pakisaji BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Palur BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Pamulutan Ogan Ilir BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Pejagoan Kebumen Proyek BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Pekalongan Bojong Proyek BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Plant Admixture Gresik Kebomas', 'lokasi' => ''],
            ['namaplant' => 'Plant BSP Balikpapan Balikpapan Utara', 'lokasi' => ''],
            ['namaplant' => 'Plant BSP Bontang Bontang Selatan', 'lokasi' => ''],
            ['namaplant' => 'Plant BSP Brebes Wanasari', 'lokasi' => ''],
            ['namaplant' => 'Plant BSP Jepara Mayong 2', 'lokasi' => ''],
            ['namaplant' => 'Plant BSP Lombok Tengah Batukliang', 'lokasi' => ''],
            ['namaplant' => 'Plant BSP Sumenep Saronggi', 'lokasi' => ''],
            ['namaplant' => 'Plant Jasa Concrete Pump', 'lokasi' => ''],
            ['namaplant' => 'Proyek 3_Probowangi 2', 'lokasi' => ''],
            ['namaplant' => 'Proyek BSP Barru Balusu', 'lokasi' => ''],
            ['namaplant' => 'Proyek BSP Bitung Madidir', 'lokasi' => ''],
            ['namaplant' => 'Proyek BSP Jepara Mayong', 'lokasi' => ''],
            ['namaplant' => 'Proyek BSP Kulon Progo Temon', 'lokasi' => ''],
            ['namaplant' => 'Proyek BSP Sidoarjo Waru2', 'lokasi' => ''],
            ['namaplant' => 'Proyek BSP Tuban Jenu', 'lokasi' => ''],
            ['namaplant' => 'Pujut BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Pulo Bandring Asahan Proyek BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Purwokerto BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Sayung BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Sidoarjo BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Tangerang Benda Proyek BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Tangerang Kelapa Dua Proyek BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Tikala Manado BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Tol Serang Panimbang Proyek BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Tol Solo Yogya Proyek BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Tuban Sumber Arum BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Ungaran Timur BSP Barang Jadi', 'lokasi' => ''],
            ['namaplant' => 'Wanasari BSP Barang Jadi', 'lokasi' => ''],
        ];

        $sbbCount = 1;
        $vubCount = 1;

        foreach ($plants as $plant) {
            $isSbb = $plant['namaplant'] === mb_strtoupper($plant['namaplant'], 'UTF-8');

            DB::table('plant')->insert([
                'idaub' => $isSbb ? 1 : 2,
                'namaplant' => $plant['namaplant'],
                'kodeplant' => $isSbb ? 'SBB' . $sbbCount++ : 'VUB' . $vubCount++,
                'lokasi' => $plant['lokasi'],
                'status' => 'aktif',
            ]);
        }
    }
}